micronaut:
  application:
    name: buyOycParkingService
  server:
    port: 8085

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    dialect: H2

jpa:
  default:
    entity-scan:
      packages: 'org.jesperancinha.buy.oyc.commons.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
