micronaut:
  application:
    name: buyOycParkingService
  server:
    port: 8086
    context-path: /api/yucca-parking

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

r2dbc:
  datasources:
    default:
      schema-generate: NONE
      dialect: POSTGRES
      url: r2dbc:postgresql://kong@${POSTGRESQL_HOST}:5432/yucca?currentSchema=ticket
      username: kong
      password: kong

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false
