micronaut:
  application:
    name: buyOycTicketService
  server:
    port: 8086

r2dbc:
  datasources:
    default:
      schema-generate: NONE
      dialect: POSTGRES
      url: r2dbc:postgresql://admin@postgres:5432/yucca?currentSchema=ticket
      username: kong
      password: kong

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false