micronaut:
  application:
    name: buyOycTicketService
  server:
    port: 8086

r2dbc:
  datasources:
    default:
      schema-generate: NONE
      dialect: POSTGRES
      url: r2dbc:postgresql://kong@localhost:5432/yucca?currentSchema=ticket
      username: kong
      password: kong

flyway:
  datasources:
    default:
      enabled: true

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false

redis:
    uri: redis://localhost
    timeout: 30s

buy.oyc.catering:
    url: /api/yucca-catering
    port: 8000
    host: localhost

buy.oyc.concert:
    url: /api/yucca-concert
    port: 8000
    host: localhost

buy.oyc.parking:
    url: /api/yucca-parking
    port: 8000
    host: localhost
