micronaut:
  application:
    name: buyOycTicketService
  server:
    port: 8086

r2dbc:
  datasources:
    default:
      schema-generate: NONE
      dialect: POSTGRES
      url: r2dbc:postgresql://kong@localhost:5432/yucca?currentSchema=ticket
      username: kong
      password: kong

flyway:
  datasources:
    default:
      enabled: false

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false


redis:
    uri: redis://localhost
    io-thread-pool-size: 5
    computation-thread-pool-size: 4
    caches:
        my-cache:
            expire-after-write: 1h
