version: '3.3'

services:
    buy-oyc-parking:
      hostname: buy-oyc-parking
      build:
        context: buy-oyc-parking-service/.

    buy-oyc-ticket:
      hostname: buy-oyc-ticket
      build:
        context: buy-oyc-ticket-service/.

    buy-oyc-catering:
      hostname: buy-oyc-catering
      build:
        context: buy-oyc-catering-service/.

    buy-oyc-nginx:
      hostname: buy-oyc-nginx
      build:
        context: ./buy-odd-yucca-gui/.
      ports:
        - "8080:8080"
      restart: on-failure
      environment:
        - KONG_SERVICE_IP=${KONG_SERVICE_IP}
      deploy:
        resources:
          limits:
            memory: 300M
          reservations:
            memory: 300M
