x-kong-config: &kong-env
  KONG_DATABASE: ${KONG_DATABASE:-off}
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_HOST: db
  KONG_PG_USER: ${KONG_PG_USER:-kong}
  KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password

volumes:
  kong_data: { }
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  yucca-net:
    external: false
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}

services:
  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap && kong migrations up && kong migrations finish
    profiles: [ "database" ]
    depends_on:
      - db
    environment:
      <<: *kong-env
    secrets:
      - kong_postgres_password
    networks:
      - yucca-net
    restart: on-failure

  kong:
    hostname: kong
    container_name: kong
    image: "${KONG_DOCKER_TAG:-kong:2.6.0}"
    user: "${KONG_USER:-kong}"
    environment:
      <<: *kong-env
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:8000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:8001}"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
      KONG_ADMIN_GUI_URL: "http://0.0.0.0:8002"
      KONG_PORTAL_GUI_HOST: "0.0.0.0:8003"
      KONG_PORTAL: "on"
    restart: on-failure
    depends_on:
      - db
    secrets:
      - kong_postgres_password
    networks:
      yucca-net:
        ipv4_address: ${KONG_SERVICE_IP}
    ports:
      # The following two environment variables default to an insecure value (0.0.0.0)
      # according to the CIS Security test.
      - "8000:8000"
      - "${KONG_INBOUND_SSL_PROXY_LISTEN:-0.0.0.0}:8443:8443/tcp"
      # Making them mandatory but undefined, like so would be backwards-breaking:
      # - "${KONG_INBOUND_PROXY_LISTEN?Missing inbound proxy host}:8000:8000/tcp"
      # - "${KONG_INBOUND_SSL_PROXY_LISTEN?Missing inbound proxy ssl host}:8443:8443/tcp"
      # Alternative is deactivating check 5.13 in the security bench, if we consider Kong's own config to be enough security here

      - "127.0.0.1:8001:8001/tcp"
      - "127.0.0.1:8444:8444/tcp"
      - "8002:8002"
      - "8003:8003"
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 20
    read_only: true
    volumes:
      - ./kong_prefix:${KONG_PREFIX:-/var/run/kong}
      - ./kong_tmp:/tmp
      - ./kong:/opt/kong
      - ./kong/kong-migration.sh:/opt/kong/kong-migration.sh
    security_opt:
      - no-new-privileges

  db:
    hostname: db
    container_name: db
    image: postgres:14.1
    profiles: [ "database" ]
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD_FILE: /run/secrets/kong_postgres_password
      POSTGRES_MULTIPLE_DATABASES: yucca
    secrets:
      - kong_postgres_password
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    ports:
      - "5432:5432"
    networks:
      - yucca-net
    volumes:
      - ./kong_data:/var/lib/postgresql/data
      - ./docker-images/docker-psql:/docker-entrypoint-initdb.d
      - ./docker-images/docker-psql/multiple:/docker-entrypoint-initdb.d/multiple

  localstack:
    image: localstack/localstack:0.13.0
    hostname: localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8090:8090"
    environment:
      - SERVICES=${AWS_SERVICES}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8090
      - DEFAULT_REGION=eu-central-1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - START_WEB=1
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "http://localhost:4566/health"]
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    networks:
      - yucca-net

  buy-oyc-parking:
    hostname: buy-oyc-parking
    container_name: buy-oyc-parking
    build:
      context: buy-oyc-parking-service/.
    networks:
      yucca-net:
        ipv4_address: ${YUCCA_PARKING_SERVICE_IP}

  buy-oyc-ticket:
    hostname: buy-oyc-ticket
    container_name: buy-oyc-ticket
    build:
      context: buy-oyc-ticket-service/.
    networks:
      yucca-net:
        ipv4_address: ${YUCCA_TICKET_SERVICE_IP}

  buy-oyc-catering:
    hostname: buy-oyc-catering
    container_name: buy-oyc-catering
    build:
      context: buy-oyc-catering-service/.
    networks:
      yucca-net:
        ipv4_address: ${YUCCA_CATERING_SERVICE_IP}


  buy-oyc-nginx:
    hostname: buy-oyc-nginx
    container_name: buy-oyc-nginx
    build:
      context: ./buy-odd-yucca-gui/.
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - KONG_SERVICE_IP=${KONG_SERVICE_IP}
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M
    networks:
      yucca-net:
        ipv4_address: ${NGINX_SERVICE_IP}

secrets:
  kong_postgres_password:
    file: ./password