x-kong-config: &kong-env
  KONG_DATABASE: ${KONG_DATABASE:-off}
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_HOST: ${POSTGRESQL_HOST:-yucca-db}
  KONG_PG_USER: ${KONG_PG_USER:-kong}
  KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password

volumes:
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  yucca-net:

services:
  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap && kong migrations up && kong migrations finish
    depends_on:
      yucca-db:
        condition: service_healthy
    environment:
      <<: *kong-env
    secrets:
      - kong_postgres_password
    networks:
      - yucca-net
    restart: on-failure

  kong:
    hostname: kong
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    depends_on:
      yucca-db:
        condition: service_healthy
      buy-oyc-api:
        condition: service_healthy
      buy-oyc-ticket:
        condition: service_healthy
      buy-oyc-concert:
        condition: service_healthy
      buy-oyc-catering:
        condition: service_healthy
      buy-oyc-parking:
        condition: service_healthy
      kong-migrations-up:
        condition: service_completed_successfully
    user: root:1000
    environment:
      <<: *kong-env
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:8000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:8001}"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
      KONG_ADMIN_GUI_URL: "http://0.0.0.0:8002"
      KONG_PORTAL_GUI_HOST: "0.0.0.0:8003"
      KONG_PORTAL: "on"
    restart: on-failure
    secrets:
      - kong_postgres_password
    expose:
      - 8000
      - 8001
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 0s
    volumes:
      - ./kong:/opt/kong
      - ./kong/kong-migration.sh:/opt/kong/kong-migration.sh
    security_opt:
      - no-new-privileges
    networks:
      yucca-net:

  yucca-db:
    hostname: yucca-db
    image: postgres:14.2
    user: "postgres"
    command: postgres -c listen_addresses='*' -c 'max_connections=400' -c 'shared_buffers=100MB'
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD_FILE: /run/secrets/kong_postgres_password
      POSTGRES_MULTIPLE_DATABASES: yucca
    secrets:
      - kong_postgres_password
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}" ]
      interval: 5s
      timeout: 180s
      retries: 20
      start_period: 0s
    restart: on-failure
    expose:
      - 5432
    volumes:
      - ./docker-images/docker-psql:/docker-entrypoint-initdb.d
      - ./docker-images/docker-psql/multiple:/docker-entrypoint-initdb.d/multiple
    privileged: true
    networks:
      yucca-net:

  buy-oyc-ticket:
    hostname: buy-oyc-ticket
    depends_on:
        yucca-db:
          condition: service_healthy
    build:
      context: buy-oyc-ticket-service/.
    environment:
      REDIS_HOST: redis
      POSTGRESQL_HOST: yucca-db
      KONG_SERVICE_IP: kong
    expose:
      - 8084
    networks:
      yucca-net:
    healthcheck:
      test: ["CMD", "curl", "--silent", "http://127.0.0.1:8084/swagger/views/swagger-ui/index.html"]
      interval: 5s
      timeout: 240s
      retries: 60

  buy-oyc-concert:
    hostname: buy-oyc-concert
    depends_on:
        yucca-db:
          condition: service_healthy
    build:
      context: buy-oyc-concert-service/.
    environment:
      REDIS_HOST: redis
      POSTGRESQL_HOST: yucca-db
    networks:
      yucca-net:
    healthcheck:
      test: ["CMD", "curl", "--silent", "http://127.0.0.1:8085/swagger/views/swagger-ui/index.html"]
      interval: 5s
      timeout: 240s
      retries: 60

  buy-oyc-parking:
    hostname: buy-oyc-parking
    depends_on:
        yucca-db:
          condition: service_healthy
    build:
      context: buy-oyc-parking-service/.
    environment:
      REDIS_HOST: redis
      POSTGRESQL_HOST: yucca-db
    networks:
      yucca-net:
    healthcheck:
      test: ["CMD", "curl", "--silent", "http://127.0.0.1:8086/swagger/views/swagger-ui/index.html"]
      interval: 5s
      timeout: 240s
      retries: 60

  buy-oyc-catering:
    hostname: buy-oyc-catering
    depends_on:
        yucca-db:
          condition: service_healthy
    build:
      context: buy-oyc-catering-service/.
    environment:
      REDIS_HOST: redis
      POSTGRESQL_HOST: yucca-db
    networks:
      yucca-net:
    healthcheck:
      test: ["CMD", "curl", "--silent", "http://127.0.0.1:8087/swagger/views/swagger-ui/index.html"]
      interval: 5s
      timeout: 240s
      retries: 60

  buy-oyc-api:
    hostname: buy-oyc-api
    depends_on:
        yucca-db:
          condition: service_healthy
    build:
      context: buy-oyc-api-service/.
    environment:
      REDIS_HOST: redis
      POSTGRESQL_HOST: yucca-db
      KONG_SERVICE_IP: kong
    networks:
      yucca-net:
    healthcheck:
      test: ["CMD", "curl", "--silent", "http://127.0.0.1:8088/swagger/views/swagger-ui/index.html"]
      interval: 5s
      timeout: 240s
      retries: 60

  buy-oyc-nginx:
    hostname: buy-oyc-nginx
    build:
      context: ./buy-odd-yucca-gui/.
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - KONG_SERVICE_IP=kong
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M
    networks:
      yucca-net:
    depends_on:
      kong:
        condition: service_healthy

  redis:
    image: redis
    ports:
       - "6379:6379"
    networks:
      yucca-net:

secrets:
  kong_postgres_password:
    file: ./password
