name: Build on PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Build and Test
          run:  mvn clean install jacoco:prepare-agent package jacoco:report

        - name: Maven OWASP Security Check
          run: mvn clean install -Powasp

        - name: NPM Snyk Security Check
          run: cd buy-odd-yucca-gui && yarn && npm i -g snyk && npm run snyk
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
