name: BOYC Build and Chain Test

on: push

jobs:
  build-chain-regression-test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 19
          uses: actions/setup-java@v3
          with:
            java-version: '19'
            distribution: 'adopt'
        - uses: actions/setup-node@v3
          with:
            node-version: '18'

        - name: Build Front End Application
          run: cd buy-odd-yucca-gui && yarn

        - name: Integration Chain Tests
          uses: nick-fields/retry@v2
          with:
            max_attempts: 3
            retry_on: error
            timeout_seconds: 2400
            command: |
              make build-integration
