name: BOYC Build, Test, Coverage and Report

on:
  push:
    branches: [ master ]
  pull_request_target:
    types:
      - closed

jobs:
  build-test-coverage-report:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 21
          uses: actions/setup-java@v3
          with:
            java-version: '21'
            distribution: 'adopt'
        - uses: actions/setup-node@v3
          with:
            node-version: '18'

        - name: Install Jest
          run: cd buy-odd-yucca-gui && yarn && yarn add jest --dev

        - name: Node Coverage
          run: cd buy-odd-yucca-gui && npm run coverage

        - name: Build and Test
          uses: nick-fields/retry@v2
          with:
            max_attempts: 2
            retry_on: error
            timeout_seconds: 2400
            command: |
              make report

        - name: Coverage Reports
          run: mvn omni-coveragereporter:report
          env:
             COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
             CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
             CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
