name: BOYC Build on PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Build and Test
          uses: nick-fields/retry@v2
          with:
            max_attempts: 2
            retry_on: error
            timeout_seconds: 2400
            command: |
              mvn clean install jacoco:prepare-agent package jacoco:report
