name: BOYC Build, Test, Coverage and Report

on:
  push:
    branches: [ master ]
  pull_request_target:
    types:
      - closed

jobs:
  build-test-coverage-report:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
        - uses: actions/setup-node@v3
          with:
            node-version: '16'

        - name: Install Jest
          run: cd buy-odd-yucca-gui && yarn && yarn add jest --dev

        - name: Node Coverage
          run: cd buy-odd-yucca-gui && npm run coverage

        - name: Build and Test
          run:  mvn clean install jacoco:prepare-agent package jacoco:report

        - name: Coverage Reports
          run: mvn omni-coveragereporter:report
          env:
             COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
             CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
             CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
