name: Build, Test, Coverage and Report

on:
  push:
    branches: [ master ]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
        - uses: actions/setup-node@v3
          with:
            node-version: '16'

        - name: Build NPM
          run: cd buy-odd-yucca-gui && yarn

        - name: Build MAVEN
          run:  mvn clean install -DskipTests

        - name: Maven OWASP Security Check
          run: mvn clean install -Powasp

        - name: NPM Snyk Security Check
          run: cd buy-odd-yucca-gui && yarn && npm i -g snyk && npm run snyk
          env:
             SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
