name: BOYC Security Checks

on: push

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'adopt'
        - uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Build NPM
          run: cd buy-odd-yucca-gui && yarn

        - name: Build MAVEN
          run:  mvn clean install -DskipTests

        - name: Maven OWASP Security Check
          run: mvn clean install -Powasp

        - name: NPM Snyk Security Check
          run: cd buy-odd-yucca-gui && yarn && npm i -g snyk && npm run snyk
          env:
             SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
