name: Build and Chain Test

on: push

jobs:
  build-chain-regression-test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'
        - uses: actions/setup-node@v2
          with:
            node-version: '16'

        - name: Build Front End Application
          run: cd buy-odd-yucca-gui && yarn

        - name: Integration Chain Tests
          run: make build-integration
