name: BOYC Build and Chain Test

on: push

jobs:
  build-chain-regression-test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'adopt'
        - uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Build Front End Application
          run: cd buy-odd-yucca-gui && yarn

        - name: Create alias
          run: alias docker-compose="docker compose"

        - name: Integration Chain Tests
          uses: nick-fields/retry@v3
          with:
            max_attempts: 5
            retry_on: error
            timeout_seconds: 2400
            command: |
              make build-integration
